# Interface dependencies.
import intf_libs = libmm-gio%lib{mm-gio}

# Implementation dependencies.
import impl_libs = libmm-glib%lib{mm-glib}

lib{mm-cairo}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "/LIBPATH:C:/gnome/lib"
cxx.poptions =+ "-D_USE_MATH_DEFINES"

{hbmia obja}{*}: cxx.poptions += -DLIBMM_CAIRO_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMM_CAIRO_SHARED_BUILD

# Export options.
#
lib{mm-cairo}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mm-cairo}: cxx.export.poptions += -DLIBMM_CAIRO_STATIC
libs{mm-cairo}: cxx.export.poptions += -DLIBMM_CAIRO_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mm-cairo}: bin.lib.version = "-$version.project_id"
else
  lib{mm-cairo}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmm-cairo/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmm-cairo/
  install.subdirs = true
}
