intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{mm-glib}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBMM_GLIB_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMM_GLIB_SHARED_BUILD

# Export options.
#
lib{mm-glib}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mm-glib}: cxx.export.poptions += -DLIBMM_GLIB_STATIC
libs{mm-glib}: cxx.export.poptions += -DLIBMM_GLIB_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mm-glib}: bin.lib.version = "-$version.project_id"
else
  lib{mm-glib}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmm-glib/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmm-glib/
  install.subdirs = true
}
