intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libmm-adw%lib{mm-adw}
import intf_libs += libmm-cairo%lib{mm-cairo}
import intf_libs += libmm-gdk%lib{mm-gdk}
import intf_libs += libmm-gio%lib{mm-gio}
import intf_libs += libmm-glib%lib{mm-glib}
import intf_libs += libmm-gtk%lib{mm-gtk}
import intf_libs += libmm-pango%lib{mm-pango}

lib{mm}: {hxx ixx txx}{** -version} \
         {hxx}{version}             \
         $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "/LIBPATH:C:/Users/wroy/Documents/Gnome/lib"

# Export options.
#
lib{mm}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# Install into the libmm/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmm/
  install.subdirs = true
}
