libs =

import libs += libmm-adw%lib{mm-adw}
import libs += libmm-gtk%lib{mm-gtk}
import libs += libmm-gdk%lib{mm-gdk}
import libs += libmm-gio%lib{mm-gio}
import libs += libmm-glib%lib{mm-glib}
import libs += libmm-cairo%lib{mm-cairo}
import libs += libmm-pango%lib{mm-pango}

exe{test-animation}: {hxx ixx txx cxx}{**} $libs testscript{**}
