libs =

import libs += libmm-gtk%lib{mm-gtk}
import libs += libmm-gdk%lib{mm-gdk}
import libs += libmm-glib%lib{mm-glib}
import libs += libmm-gio%lib{mm-gio}
import libs += libmm-pango%lib{mm-pango}
import libs += libmm-cairo%lib{mm-cairo}

exe{tree_model_iterator}: {hxx ixx txx cxx}{**} $libs testscript{**}
