import libs = libmm-gtk%lib{mm-gtk}     \
              libmm-gdk%lib{mm-gdk}     \
              libmm-glib%lib{mm-glib}   \
              libmm-gio%lib{mm-gio}     \
              libmm-pango%lib{mm-pango} \
              libmm-cairo%lib{mm-cairo} \

exe{property_notification}: {hxx ixx txx cxx}{**} $libs testscript{**}
