# Interface dependencies.
#
import intf_libs = libadwaita-1.0%lib{adwaita-1}

# Implementation dependencies.
#
import impl_libs = libmm-gtk%lib{mm-gtk}     \
                   libmm-gdk%lib{mm-gdk}     \
                   libmm-gio%lib{mm-gio}     \
                   libmm-glib%lib{mm-glib}   \
                   libmm-cairo%lib{mm-cairo} \
                   libmm-pango%lib{mm-pango} \

lib{mm-adw}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "/LIBPATH:C:/gnome/lib"

{hbmia obja}{*}: cxx.poptions += -DLIBMM_ADW_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMM_ADW_SHARED_BUILD

# Export options.
#
lib{mm-adw}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mm-adw}: cxx.export.poptions += -DLIBMM_ADW_STATIC
libs{mm-adw}: cxx.export.poptions += -DLIBMM_ADW_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mm-adw}: bin.lib.version = "-$version.project_id"
else
  lib{mm-adw}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmm-adw/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmm-adw/
  install.subdirs = true
}
