# Interface dependencies.
#
import intf_libs = pango%lib{pango}           \
                   pangocairo%lib{pangocairo}

# Implementation dependencies.
#
import impl_libs = libmm-glib%lib{mm-glib}   \
                   libmm-gio%lib{mm-gio}     \
                   libmm-cairo%lib{mm-cairo}

lib{mm-pango}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "/LIBPATH:C:/gnome/lib"

{hbmia obja}{*}: cxx.poptions += -DLIBMM_PANGO_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMM_PANGO_SHARED_BUILD

# Export options.
#
lib{mm-pango}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mm-pango}: cxx.export.poptions += -DLIBMM_PANGO_STATIC
libs{mm-pango}: cxx.export.poptions += -DLIBMM_PANGO_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mm-pango}: bin.lib.version = "-$version.project_id"
else
  lib{mm-pango}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libmm-pango/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmm-pango/
  install.subdirs = true
}
