// SPDX-License-Identifier: LGPL-2.1-or-later

#ifndef _GTKMM_H
#define _GTKMM_H

extern const int gtkmm_major_version;
extern const int gtkmm_minor_version;
extern const int gtkmm_micro_version;

#include <libmm-glib/mm-glib.hxx>

#include <libmm-gdk/mm-gdk.hxx>

#include <libmm-gtk/aboutdialog.hxx>
#include <libmm-gtk/accelerator.hxx>
#include <libmm-gtk/accelkey.hxx>
#include <libmm-gtk/actionable.hxx>
#include <libmm-gtk/actionbar.hxx>
#include <libmm-gtk/adjustment.hxx>
#include <libmm-gtk/alertdialog.hxx>
#include <libmm-gtk/appchooserbutton.hxx>
#include <libmm-gtk/appchooserdialog.hxx>
#include <libmm-gtk/appchooserwidget.hxx>
#include <libmm-gtk/application.hxx>
#include <libmm-gtk/applicationwindow.hxx>
#include <libmm-gtk/aspectframe.hxx>
#include <libmm-gtk/assistant.hxx>
#include <libmm-gtk/atcontext.hxx>
#include <libmm-gtk/binlayout.hxx>
#include <libmm-gtk/boolfilter.hxx>
#include <libmm-gtk/border.hxx>
#include <libmm-gtk/box.hxx>
#include <libmm-gtk/boxlayout.hxx>
#include <libmm-gtk/builder.hxx>
#include <libmm-gtk/button.hxx>
#include <libmm-gtk/calendar.hxx>
#include <libmm-gtk/cellarea.hxx>
#include <libmm-gtk/cellareabox.hxx>
#include <libmm-gtk/cellareacontext.hxx>
#include <libmm-gtk/cellrenderer.hxx>
#include <libmm-gtk/cellrendereraccel.hxx>
#include <libmm-gtk/cellrenderercombo.hxx>
#include <libmm-gtk/cellrendererpixbuf.hxx>
#include <libmm-gtk/cellrendererprogress.hxx>
#include <libmm-gtk/cellrendererspin.hxx>
#include <libmm-gtk/cellrendererspinner.hxx>
#include <libmm-gtk/cellrenderertext.hxx>
#include <libmm-gtk/cellrenderertoggle.hxx>
#include <libmm-gtk/cellview.hxx>
#include <libmm-gtk/centerbox.hxx>
#include <libmm-gtk/centerlayout.hxx>
#include <libmm-gtk/checkbutton.hxx>
#include <libmm-gtk/colorbutton.hxx>
#include <libmm-gtk/colorchooser.hxx>
#include <libmm-gtk/colorchooserdialog.hxx>
#include <libmm-gtk/colordialogbutton.hxx>
#include <libmm-gtk/columnview.hxx>
#include <libmm-gtk/columnviewsorter.hxx>
#include <libmm-gtk/combobox.hxx>
#include <libmm-gtk/comboboxtext.hxx>
#include <libmm-gtk/constraintlayout.hxx>
#include <libmm-gtk/cssprovider.hxx>
#include <libmm-gtk/csssection.hxx>
#include <libmm-gtk/dialog.hxx>
#include <libmm-gtk/directorylist.hxx>
#include <libmm-gtk/dragicon.hxx>
#include <libmm-gtk/dragsource.hxx>
#include <libmm-gtk/drawingarea.hxx>
#include <libmm-gtk/dropcontrollermotion.hxx>
#include <libmm-gtk/dropdown.hxx>
#include <libmm-gtk/droptarget.hxx>
#include <libmm-gtk/droptargetasync.hxx>
#include <libmm-gtk/editablelabel.hxx>
#include <libmm-gtk/emojichooser.hxx>
#include <libmm-gtk/entry.hxx>
#include <libmm-gtk/enums.hxx>
#include <libmm-gtk/error.hxx>
#include <libmm-gtk/eventcontroller.hxx>
#include <libmm-gtk/eventcontrollerfocus.hxx>
#include <libmm-gtk/eventcontrollerkey.hxx>
#include <libmm-gtk/eventcontrollermotion.hxx>
#include <libmm-gtk/eventcontrollerscroll.hxx>
#include <libmm-gtk/expander.hxx>
#include <libmm-gtk/filechooser.hxx>
#include <libmm-gtk/filechooserdialog.hxx>
#include <libmm-gtk/filechoosernative.hxx>
#include <libmm-gtk/filechooserwidget.hxx>
#include <libmm-gtk/filedialog.hxx>
#include <libmm-gtk/filefilter.hxx>
#include <libmm-gtk/filelauncher.hxx>
#include <libmm-gtk/filterlistmodel.hxx>
#include <libmm-gtk/fixed.hxx>
#include <libmm-gtk/flattenlistmodel.hxx>
#include <libmm-gtk/flowbox.hxx>
#include <libmm-gtk/flowboxchild.hxx>
#include <libmm-gtk/fontbutton.hxx>
#include <libmm-gtk/fontchooser.hxx>
#include <libmm-gtk/fontchooserdialog.hxx>
#include <libmm-gtk/fontchooserwidget.hxx>
#include <libmm-gtk/fontdialogbutton.hxx>
#include <libmm-gtk/frame.hxx>
#include <libmm-gtk/gesture.hxx>
#include <libmm-gtk/gestureclick.hxx>
#include <libmm-gtk/gesturedrag.hxx>
#include <libmm-gtk/gesturelongpress.hxx>
#include <libmm-gtk/gesturepan.hxx>
#include <libmm-gtk/gesturerotate.hxx>
#include <libmm-gtk/gesturesingle.hxx>
#include <libmm-gtk/gesturestylus.hxx>
#include <libmm-gtk/gestureswipe.hxx>
#include <libmm-gtk/gesturezoom.hxx>
#include <libmm-gtk/glarea.hxx>
#include <libmm-gtk/grid.hxx>
#include <libmm-gtk/gridlayout.hxx>
#include <libmm-gtk/gridlayoutchild.hxx>
#include <libmm-gtk/gridview.hxx>
#include <libmm-gtk/headerbar.hxx>
#include <libmm-gtk/icontheme.hxx>
#include <libmm-gtk/iconview.hxx>
#include <libmm-gtk/image.hxx>
#include <libmm-gtk/infobar.hxx>
#include <libmm-gtk/inscription.hxx>
#include <libmm-gtk/label.hxx>
#include <libmm-gtk/layoutchild.hxx>
#include <libmm-gtk/layoutmanager.hxx>
#include <libmm-gtk/levelbar.hxx>
#include <libmm-gtk/linkbutton.hxx>
#include <libmm-gtk/listbox.hxx>
#include <libmm-gtk/listboxrow.hxx>
#include <libmm-gtk/liststore.hxx>
#include <libmm-gtk/listview.hxx>
#include <libmm-gtk/listviewtext.hxx>
#include <libmm-gtk/mediacontrols.hxx>
#include <libmm-gtk/mediafile.hxx>
#include <libmm-gtk/menubutton.hxx>
#include <libmm-gtk/messagedialog.hxx>
#include <libmm-gtk/multifilter.hxx>
#include <libmm-gtk/multiselection.hxx>
#include <libmm-gtk/multisorter.hxx>
#include <libmm-gtk/noselection.hxx>
#include <libmm-gtk/notebook.hxx>
#include <libmm-gtk/numericsorter.hxx>
#include <libmm-gtk/object.hxx>
#include <libmm-gtk/overlay.hxx>
#include <libmm-gtk/padcontroller.hxx>
#include <libmm-gtk/pagesetup.hxx>
#include <libmm-gtk/paned.hxx>
#ifndef G_OS_WIN32
  #include <libmm-gtk/pagesetupunixdialog.hxx>
#endif
#include <libmm-gtk/papersize.hxx>
#include <libmm-gtk/passwordentry.hxx>
#include <libmm-gtk/picture.hxx>
#include <libmm-gtk/popover.hxx>
#include <libmm-gtk/popovermenu.hxx>
#include <libmm-gtk/popovermenubar.hxx>
#include <libmm-gtk/printcontext.hxx>
#ifndef G_OS_WIN32
  #include <libmm-gtk/printer.hxx>
  #include <libmm-gtk/printjob.hxx>
#endif
#include <libmm-gtk/printoperation.hxx>
#include <libmm-gtk/printoperationpreview.hxx>
#include <libmm-gtk/printsettings.hxx>
#ifndef G_OS_WIN32
  #include <libmm-gtk/printunixdialog.hxx>
#endif
#include <libmm-gtk/progressbar.hxx>
#include <libmm-gtk/range.hxx>
#include <libmm-gtk/recentinfo.hxx>
#include <libmm-gtk/recentmanager.hxx>
#include <libmm-gtk/revealer.hxx>
#include <libmm-gtk/scale.hxx>
#include <libmm-gtk/scalebutton.hxx>
#include <libmm-gtk/scrollbar.hxx>
#include <libmm-gtk/scrolledwindow.hxx>
#include <libmm-gtk/searchbar.hxx>
#include <libmm-gtk/searchentry.hxx>
#include <libmm-gtk/selectionfiltermodel.hxx>
#include <libmm-gtk/selectionlistmodelimpl.hxx>
#include <libmm-gtk/separator.hxx>
#include <libmm-gtk/settings.hxx>
#include <libmm-gtk/shortcutcontroller.hxx>
#include <libmm-gtk/shortcutlabel.hxx>
#include <libmm-gtk/shortcutsgroup.hxx>
#include <libmm-gtk/shortcutssection.hxx>
#include <libmm-gtk/shortcutsshortcut.hxx>
#include <libmm-gtk/shortcutswindow.hxx>
#include <libmm-gtk/signallistitemfactory.hxx>
#include <libmm-gtk/singleselection.hxx>
#include <libmm-gtk/sizegroup.hxx>
#include <libmm-gtk/slicelistmodel.hxx>
#include <libmm-gtk/snapshot.hxx>
#include <libmm-gtk/sortlistmodel.hxx>
#include <libmm-gtk/spinbutton.hxx>
#include <libmm-gtk/spinner.hxx>
#include <libmm-gtk/stack.hxx>
#include <libmm-gtk/stacksidebar.hxx>
#include <libmm-gtk/stackswitcher.hxx>
#include <libmm-gtk/statusbar.hxx>
#include <libmm-gtk/stringfilter.hxx>
#include <libmm-gtk/stringlist.hxx>
#include <libmm-gtk/stringobject.hxx>
#include <libmm-gtk/stringsorter.hxx>
#include <libmm-gtk/stylecontext.hxx>
#include <libmm-gtk/switch.hxx>
#include <libmm-gtk/text.hxx>
#include <libmm-gtk/textbuffer.hxx>
#include <libmm-gtk/textchildanchor.hxx>
#include <libmm-gtk/textiter.hxx>
#include <libmm-gtk/textmark.hxx>
#include <libmm-gtk/texttag.hxx>
#include <libmm-gtk/texttagtable.hxx>
#include <libmm-gtk/textview.hxx>
#include <libmm-gtk/togglebutton.hxx>
#include <libmm-gtk/tooltip.hxx>
#include <libmm-gtk/treeexpander.hxx>
#include <libmm-gtk/treelistmodel.hxx>
#include <libmm-gtk/treemodel.hxx>
#include <libmm-gtk/treemodelfilter.hxx>
#include <libmm-gtk/treemodelsort.hxx>
#include <libmm-gtk/treepath.hxx>
#include <libmm-gtk/treerowreference.hxx>
#include <libmm-gtk/treeselection.hxx>
#include <libmm-gtk/treestore.hxx>
#include <libmm-gtk/treeview.hxx>
#include <libmm-gtk/treeviewcolumn.hxx>
#include <libmm-gtk/urilauncher.hxx>
#include <libmm-gtk/version.hxx>
#include <libmm-gtk/video.hxx>
#include <libmm-gtk/viewport.hxx>
#include <libmm-gtk/volumebutton.hxx>
#include <libmm-gtk/widget.hxx>
#include <libmm-gtk/widgetpaintable.hxx>
#include <libmm-gtk/window.hxx>
#include <libmm-gtk/windowcontrols.hxx>
#include <libmm-gtk/windowhandle.hxx>

#endif
