import libs = libmm-adw%lib{mm-adw}     \
              libmm-gtk%lib{mm-gtk}     \
              libmm-gdk%lib{mm-gdk}     \
              libmm-gio%lib{mm-gio}     \
              libmm-glib%lib{mm-glib}   \
              libmm-cairo%lib{mm-cairo} \
              libmm-pango%lib{mm-pango} \

exe{test-window-title}: {hxx ixx txx cxx}{**} $libs testscript{**}
